language: ruby
rvm:
  - "2.2.1"
env:
  - TAG_FILTER=~js DB=postgres RAILS_ENV=test
  - TAG_FILTER=js DB=postgres RAILS_ENV=test
install: touch ~/do_not_run_bundle
script: "bundle exec rspec --tag $TAG_FILTER && sleep 1"
