language: ruby
rvm:
  - "2.2.1"
env:
  - TAG_FILTER=~js DB=postgres RAILS_ENV=test
  - TAG_FILTER=js DB=postgres RAILS_ENV=test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script: "bundle exec rspec --tag $TAG_FILTER && sleep 1"
